project: vqgan
name: vqgan-flower-v3

train_params:
  seed: 42
  batch_size: 8
  grad_accumulation: 4
  precision: bf16-mixed
  optimizer:
    use_8bit: true
    lr: 4.5e-6
  disc_start: 40000

data:
  paths:
    - /home/archimickey/Projects/VQGAN/data/102flower/edited
  img_size: 128

model:
  model_ckpt: /home/archimickey/Projects/VQGAN/checkpoints/20230803_024603/checkpoint_10000.pt
  loading_modules:
    - vqvae
  vqvae:
    dim: 64
    dim_mults: [1, 1, 2, 4, 8]
    resnet_block_groups: 16
    codebook_dim: 512
    codebook_size: 1024
  discriminator:
    input_nc: 3
    ndf: 64
    n_layers: 3
  loss:
    perceptual_weight: 1
    adv_weight: 0.2

logger:
  project: ${project}
  checkpoint_path: /home/archimickey/Projects/VQGAN/checkpoints
  save_interval: 10000
  log_img_interval: 1
  loss_names:
    - generator/recon_loss
    - generator/perceptual_loss
    - generator/perceptual_recon_loss
    - generator/commit_loss
    - generator/adv_loss
    - generator/total_loss
    - discriminator/loss
